version: '3.8'
services:
  webdriver-tests:
    image: webdriver-tests:1.0
    networks:
      - webdriver

    build:
      context: .
      dockerfile: Dockerfile
     
    volumes:
      - ./report:/app/report

    working_dir: /app

networks:
  webdriver:
