name: Run in Docker-Compose

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Test
      run: docker-compose up
      
    - name: Create test summary
      uses: test-summary/action@v1.0
      with:
        paths: report/results.xml
      if: always()
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "report/results.xml"
