name: Run in pure Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  checks: write
  pull-requests: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mytest
    
    - name: Run Test
      run: docker run -it mytest -v ./report:/app/report
      
    - name: Create test summary
      uses: test-summary/action@v1.0
      with:
        paths: report/results.xml
      if: always()
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "report/results.xml"
